language: php
php:
  - "7.1"
  - "7.2"
  - "7.3"

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"

install:
  - travis_retry composer install

script:
  - ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests
  - ./vendor/bin/phpstan analyse -l 7 tests # Only tests folder for now. As src folder will break

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email: false
